name: CI - oldest supported php

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'
      - uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.OS }}-build-oldest-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
        env:
          COMPOSER: "composer-php-oldest.json"
        with:
          php_version: "7.1"
          version: 1
      - name: PHP Lint
        run: vendor/bin/phplint --exclude=vendor
      - name: PHP Unit
        run: vendor/phpunit/phpunit/phpunit -c phpunit.xml