name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
      - name: PHP Lint
        run: vendor/bin/phplint --exclude=vendor
      - name: PHP Unit
        run: vendor/phpunit/phpunit/phpunit -c phpunit.xml